name: Bullet Catalyst v1 (OpenAI + Grok) — Option A (wide gate)

on:
  schedule:
    # GitHub cron is UTC. 07:30 America/Los_Angeles is:
    #   • 14:30 UTC during PDT (UTC-7)
    #   • 15:30 UTC during PST (UTC-8)
    - cron: "30 14 * * *"  # summer (PDT)
    - cron: "30 15 * * *"  # winter (PST)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # Allow scheduler drift around 07:30 LA (minutes)
      TOLERANCE_MIN: "25"

    steps:
      - name: Gate — only run near 08:40 Los_Angeles or when manually dispatched
        id: gate
        shell: bash
        run: |
          HM=$(TZ=America/Los_Angeles date +'%H:%M')
          H=$(TZ=America/Los_Angeles date +'%H')
          M=$(TZ=America/Los_Angeles date +'%M')
          MINUTES=$((10#$H*60 + 10#$M))
          TARGET=$((7*60 + 30))
          DIFF=$(( MINUTES - TARGET ))
          ABS=${DIFF#-}
          TOL=${TOLERANCE_MIN:-25}
          if [ "$ABS" -le "$TOL" ]; then OK=yes; else OK=no; fi
          echo "now=$HM" >> "$GITHUB_OUTPUT"
          echo "ok=$OK"  >> "$GITHUB_OUTPUT"
          echo "Local time LA: $HM (±${TOL} min -> ok=$OK)"

      - name: Debug event/time
        run: |
          echo "event=${{ github.event_name }}"
          echo "cron='${{ github.event.schedule }}'"
          date -u '+UTC: %Y-%m-%d %H:%M'
          TZ=America/Los_Angeles date '+LA : %Y-%m-%d %H:%M'

      - uses: actions/checkout@v4
        if: steps.gate.outputs.ok == 'yes' || github.event_name == 'workflow_dispatch'

      - uses: actions/setup-node@v4
        if: steps.gate.outputs.ok == 'yes' || github.event_name == 'workflow_dispatch'
        with:
          node-version: "20"

      - name: Install deps
        if: steps.gate.outputs.ok == 'yes' || github.event_name == 'workflow_dispatch'
        run: npm i --no-audit --no-fund

      - name: Run (dry-run if keys missing)
        if: steps.gate.outputs.ok == 'yes' || github.event_name == 'workflow_dispatch'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          XAI_API_KEY:    ${{ secrets.XAI_API_KEY }}
          EMAIL_FROM:     ${{ secrets.EMAIL_FROM }}
          EMAIL_TO:       ${{ secrets.EMAIL_TO }}
          SMTP_HOST:      ${{ secrets.SMTP_HOST }}
          SMTP_PORT:      ${{ secrets.SMTP_PORT }}     # "465" for SSL, "587" for STARTTLS
          SMTP_USER:      ${{ secrets.SMTP_USER }}
          SMTP_PASS:      ${{ secrets.SMTP_PASS }}
          OPENAI_MODEL:   gpt-4o-mini
          XAI_MODEL:      grok-4-fast-reasoning
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ] || [ -z "${{ secrets.XAI_API_KEY }}" ] || [ -z "${{ secrets.SMTP_PASS }}" ]; then
            echo "Secrets missing -> running DRY RUN"
            npm run test-run
          else
            npm start
          fi

      - name: Skipped (not ~08:40 LA)
        if: steps.gate.outputs.ok != 'yes' && github.event_name != 'workflow_dispatch'
        run: echo "Not 08:40±${{ env.TOLERANCE_MIN }}min America/Los_Angeles (was ${{ steps.gate.outputs.now }}). Skipping."
