name: xAI Probes

on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: "Endpoint to test (chat|responses)"
        default: "chat"
        type: choice
        options: [chat, responses]
      model:
        description: "Model ID to test"
        default: "grok-2-mini"
        type: string

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Run list-models
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
        run: node runner/xai_models.mjs
      - name: Probe selected endpoint
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          XAI_ENDPOINT: ${{ github.event.inputs.endpoint }}
          XAI_MODEL: ${{ github.event.inputs.model }}
        run: node runner/xai_probe.mjs
